package com.rxas400adm.operation.policy;

import com.rxas400adm.common.exception.BusinessException;
import com.rxas400adm.common.exception.ErrorCode;
import com.rxas400adm.operation.domain.RiskLevel;
import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 确认令牌策略：
 * - CRITICAL 及以上级别操作需要二次确认令牌
 * - 令牌生成后存储在内存缓存中，TTL 默认 5 分钟
 * - 验证后立即消费（一次性使用）
 * - 生产环境建议替换为 Redis 缓存
 */
@Slf4j
@Component
public class ConfirmationPolicy {

    /** 令牌有效期（毫秒），默认 5 分钟 */
    @Value("${rxas400.operation.confirmation-ttl-ms:300000}")
    private long confirmationTtlMs;

    /** 内存令牌缓存：token -> 过期时间戳 */
    private final Map<String, Instant> tokenCache = new ConcurrentHashMap<>();

    @PostConstruct
    void init() {
        log.info("ConfirmationPolicy initialized, TTL={}ms", confirmationTtlMs);
    }

    /**
     * 生成确认令牌并缓存。
     *
     * @return 生成的令牌字符串
     */
    public String generateConfirmationToken() {
        String token = UUID.randomUUID().toString();
        tokenCache.put(token, Instant.now().plusMillis(confirmationTtlMs));
        log.debug("Confirmation token generated: {}", token);
        return token;
    }

    /**
     * 检查确认令牌的有效性。
     * CRITICAL 及以上级别操作必须提供有效的确认令牌。
     *
     * @param riskLevel 操作风险等级
     * @param token     确认令牌
     * @throws BusinessException 如果令牌无效或已过期
     */
    public void checkConfirmation(RiskLevel riskLevel, String token) {
        if (riskLevel.ordinal() < RiskLevel.CRITICAL.ordinal()) {
            return;
        }
        if (token == null || token.isBlank()) {
            throw new BusinessException(ErrorCode.OPERATION_CONFIRMATION_REQUIRED,
                riskLevel + " level operation requires confirmation token");
        }

        // 验证令牌是否在缓存中（由系统生成）
        Instant expiry = tokenCache.remove(token);
        if (expiry == null) {
            throw new BusinessException(ErrorCode.OPERATION_CONFIRMATION_REQUIRED,
                "Invalid confirmation token: token was not generated by the system or already consumed");
        }

        // 验证令牌是否过期
        if (Instant.now().isAfter(expiry)) {
            throw new BusinessException(ErrorCode.OPERATION_CONFIRMATION_REQUIRED,
                "Confirmation token has expired");
        }

        log.debug("Confirmation token validated and consumed: {}", token);
    }

    /**
     * 清理已过期的令牌（每分钟执行一次）。
     */
    @Scheduled(fixedRate = 60000)
    public void evictExpiredTokens() {
        Instant now = Instant.now();
        tokenCache.entrySet().removeIf(entry -> now.isAfter(entry.getValue()));
    }
}