-- ============================================================
-- RXAS400ADM 数据库初始化脚本（DB2 for i / RXADMIN Library）
-- 适用于 US400CND 首次部署
-- 执行方式：通过 ACS 或 PASE db2 -f init_rxadmin.sql
-- ============================================================

SET SCHEMA RXADMIN;


-- ---------- 1. 用户表 ----------
CREATE TABLE RX_USER (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME     VARCHAR(50)  NOT NULL UNIQUE,
    PASSWORD     VARCHAR(255) NOT NULL,
    EMAIL        VARCHAR(100),
    STATUS       VARCHAR(20)  DEFAULT 'ACTIVE' NOT NULL,
    LOGIN_SOURCE VARCHAR(20)  DEFAULT 'PLATFORM',
    AS400_SERVER_ID BIGINT,
    CREATED_BY   VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_USER_USERNAME ON RX_USER (USERNAME);
CREATE INDEX IDX_USER_LOGIN_SOURCE ON RX_USER (LOGIN_SOURCE);
CREATE INDEX IDX_USER_AS400_SERVER ON RX_USER (AS400_SERVER_ID);

-- ---------- 2. 角色表 ----------
CREATE TABLE RX_ROLE (
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_CODE   VARCHAR(50)  NOT NULL,
    ROLE_NAME   VARCHAR(100),
    DESCRIPTION TEXT,
    SORT        INT DEFAULT 0 NOT NULL,
    STATUS      SMALLINT DEFAULT 1 NOT NULL
);

CREATE UNIQUE INDEX UK_ROLE_CODE ON RX_ROLE (ROLE_CODE);

-- ---------- 3. 权限表 ----------
CREATE TABLE RX_PERMISSION (
    ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PERMISSION_CODE VARCHAR(100) NOT NULL,
    PERMISSION_NAME VARCHAR(100),
    MODULE          VARCHAR(50),
    DESCRIPTION     VARCHAR(200)
);

CREATE UNIQUE INDEX UK_PERM_CODE ON RX_PERMISSION (PERMISSION_CODE);

-- ---------- 4. 用户-角色关联 ----------
CREATE TABLE RX_USER_ROLE (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

-- ---------- 5. 角色-权限关联 ----------
CREATE TABLE RX_ROLE_PERMISSION (
    ROLE_ID       BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);

-- ---------- 6. 角色-菜单关联 ----------
CREATE TABLE RX_ROLE_MENU (
    ROLE_ID BIGINT NOT NULL,
    MENU_ID BIGINT NOT NULL,
    PRIMARY KEY (ROLE_ID, MENU_ID)
);

CREATE INDEX IDX_ROLE_MENU_MENU ON RX_ROLE_MENU (MENU_ID);

-- ---------- 7. 用户-菜单直接授权 ----------
CREATE TABLE RX_USER_MENU (
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID     BIGINT NOT NULL,
    MENU_ID     BIGINT NOT NULL,
    CREATED_TIME TIMESTAMP,
    UNIQUE (USER_ID, MENU_ID)
);

CREATE INDEX IDX_UM_MENU ON RX_USER_MENU (MENU_ID);

-- ---------- 8. 菜单表 ----------
CREATE TABLE RX_MENU (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PARENT_ID    BIGINT,
    MENU_NAME    VARCHAR(64)  NOT NULL,
    MENU_TYPE    SMALLINT     DEFAULT 2 NOT NULL,
    TITLE        VARCHAR(64)  NOT NULL,
    PATH         VARCHAR(128),
    COMPONENT    VARCHAR(128),
    PERMS        VARCHAR(128),
    ICON         VARCHAR(64),
    SORT         INT          DEFAULT 0 NOT NULL,
    VISIBLE      SMALLINT     DEFAULT 1 NOT NULL,
    STATUS       SMALLINT     DEFAULT 1 NOT NULL,
    ADMIN_ONLY   SMALLINT     DEFAULT 0 NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP
);

CREATE INDEX IDX_MENU_PARENT ON RX_MENU (PARENT_ID);
CREATE INDEX IDX_MENU_STATUS ON RX_MENU (STATUS);

-- ---------- 9. 审计日志 ----------
CREATE TABLE RX_AUDIT_LOG (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_NAME    VARCHAR(50),
    ACTION       VARCHAR(50),
    MODULE       VARCHAR(50),
    TARGET       VARCHAR(200),
    IP           VARCHAR(255),
    DETAIL       CLOB,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_AUDIT_USER_TIME ON RX_AUDIT_LOG (USER_NAME, CREATED_TIME DESC);

-- ---------- 10. IBM i 服务器管理 ----------
CREATE TABLE RX_IBMI_SYSTEM (
    ID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME             VARCHAR(100) NOT NULL,
    HOST             VARCHAR(100) NOT NULL,
    PORT             INT          DEFAULT 8470,
    USERNAME         VARCHAR(50),
    PASSWORD_ENCRYPT VARCHAR(500),
    ENVIRONMENT      VARCHAR(20),
    REGION           VARCHAR(50),
    CRITICAL_LEVEL   VARCHAR(20),
    HA_GROUP         VARCHAR(50),
    SSL_ENABLED      SMALLINT     DEFAULT 0,
    DEFAULT_LIBRARIES VARCHAR(255),
    CCSID            INT          DEFAULT 37,
    ENABLED          SMALLINT     DEFAULT 1,
    DEFAULT_SERVER   SMALLINT     DEFAULT 0,
    STATUS           VARCHAR(20)  DEFAULT 'OFFLINE',
    DESCRIPTION      TEXT,
    SORT_ORDER       INT          DEFAULT 0,
    CREATED_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (NAME)
);

CREATE INDEX IDX_IBMI_SYSTEM_ENABLED_DEFAULT ON RX_IBMI_SYSTEM (ENABLED, DEFAULT_SERVER);

-- ---------- 11. AS400 连接日志 ----------
CREATE TABLE RX_AS400_CONNECTION_LOG (
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTANCE_ID BIGINT,
    SUCCESS     SMALLINT,
    MESSAGE     TEXT,
    TEST_TIME   TIMESTAMP
);

-- ---------- 12. SQL 执行历史 ----------
CREATE TABLE RX_SQL_HISTORY (
    ID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SQL_TEXT      CLOB,
    ROWS_RETURNED INT,
    COST_MS       BIGINT,
    OPERATOR      VARCHAR(50),
    CREATED_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_SQL_HISTORY_OPERATOR ON RX_SQL_HISTORY (OPERATOR);

-- ---------- 13. 作业调度 ----------
CREATE TABLE RX_JOB_SCHEDULE (
    ID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR(100) NOT NULL,
    DESCRIPTION   VARCHAR(255),
    SERVER_ID     BIGINT NOT NULL,
    SCHEDULE_TYPE VARCHAR(10)  NOT NULL,
    COMMAND       CLOB         NOT NULL,
    CRON_EXPR     VARCHAR(50)  NOT NULL,
    ENABLED       SMALLINT     DEFAULT 1 NOT NULL,
    STATUS        VARCHAR(20)  DEFAULT 'PENDING' NOT NULL,
    LAST_RUN_TIME TIMESTAMP,
    LAST_RESULT   VARCHAR(500),
    CREATED_BY    VARCHAR(50),
    CREATED_TIME  TIMESTAMP NOT NULL,
    UPDATED_TIME  TIMESTAMP
);

CREATE INDEX IDX_SCHEDULE_SERVER ON RX_JOB_SCHEDULE (SERVER_ID);

-- ---------- 14. 作业调度历史 ----------
CREATE TABLE RX_JOB_SCHEDULE_HISTORY (
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SCHEDULE_ID BIGINT NOT NULL,
    RUN_TIME    TIMESTAMP NOT NULL,
    STATUS      VARCHAR(20) NOT NULL,
    MESSAGE     VARCHAR(1000),
    COST_MS     BIGINT,
    UPDATED_TIME TIMESTAMP
);

CREATE INDEX IDX_HISTORY_SCHEDULE ON RX_JOB_SCHEDULE_HISTORY (SCHEDULE_ID);

-- ---------- 15. 登录失败记录 ----------
CREATE TABLE RX_LOGIN_ATTEMPT (
    USERNAME      VARCHAR(50) NOT NULL,
    SERVER_ID     BIGINT      DEFAULT 0 NOT NULL,
    FAILED_COUNT  INT         DEFAULT 0 NOT NULL,
    LOCKED_UNTIL  TIMESTAMP,
    LAST_FAIL_TIME TIMESTAMP,
    LAST_IP       VARCHAR(64),
    UPDATED_TIME  TIMESTAMP,
    PRIMARY KEY (USERNAME, SERVER_ID)
);

-- ---------- 16. 命令脚本 ----------
CREATE TABLE RX_COMMAND_SCRIPT (
    ID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR(100) NOT NULL,
    DESCRIPTION   VARCHAR(255),
    COMMAND       CLOB         NOT NULL,
    FAVORITE      SMALLINT     DEFAULT 0 NOT NULL,
    TAGS          VARCHAR(255),
    CREATED_BY    VARCHAR(50),
    RUN_COUNT     INT          DEFAULT 0 NOT NULL,
    LAST_RUN_TIME TIMESTAMP,
    LAST_RESULT   VARCHAR(500),
    LAST_RUN_STATUS VARCHAR(16),
    CREATED_TIME  TIMESTAMP NOT NULL,
    UPDATED_TIME  TIMESTAMP
);

CREATE INDEX IDX_SCRIPT_FAVORITE ON RX_COMMAND_SCRIPT (FAVORITE);

-- ---------- 17. 监控指标 ----------
CREATE TABLE RX_METRIC (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTANCE_ID  BIGINT,
    METRIC_TYPE  VARCHAR(50),
    METRIC_NAME  VARCHAR(100),
    METRIC_VALUE DOUBLE,
    COLLECT_TIME TIMESTAMP NOT NULL
);

CREATE INDEX IDX_METRIC_INSTANCE_TIME ON RX_METRIC (INSTANCE_ID, COLLECT_TIME DESC);
CREATE INDEX IDX_METRIC_NAME_TIME ON RX_METRIC (METRIC_NAME, COLLECT_TIME DESC);

-- ---------- 18. 指标基线 ----------
CREATE TABLE RX_METRIC_BASELINE (
    INSTANCE_ID   BIGINT      NOT NULL,
    METRIC_NAME   VARCHAR(20) NOT NULL,
    BASELINE_DATE DATE        NOT NULL,
    AVG_VALUE     DOUBLE      DEFAULT 0 NOT NULL,
    MAX_VALUE     DOUBLE      DEFAULT 0 NOT NULL,
    MIN_VALUE     DOUBLE      DEFAULT 0 NOT NULL,
    SAMPLE_COUNT  INT         DEFAULT 0 NOT NULL,
    PRIMARY KEY (INSTANCE_ID, METRIC_NAME, BASELINE_DATE)
);

-- ---------- 19. 作业历史 ----------
CREATE TABLE RX_JOB_HISTORY (
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTANCE_ID BIGINT,
    JOB_NAME    VARCHAR(100),
    JOB_USER    VARCHAR(50),
    JOB_NUMBER  VARCHAR(20),
    STATUS      VARCHAR(20),
    CPU_TIME    BIGINT,
    RECORD_TIME TIMESTAMP
);

CREATE INDEX IDX_JOB_INSTANCE ON RX_JOB_HISTORY (INSTANCE_ID, RECORD_TIME);

-- ---------- 20. 告警规则 ----------
CREATE TABLE RX_ALERT_RULE (
    ID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    METRIC_NAME      VARCHAR(100),
    OPERATOR         VARCHAR(10),
    THRESHOLD        DOUBLE,
    DURATION_SECONDS INT,
    LEVEL            VARCHAR(20),
    ENABLED          SMALLINT DEFAULT 1,
    SERVER_ID        BIGINT,
    ALERT_NAME       VARCHAR(100),
    DESCRIPTION      VARCHAR(500),
    NOTIFY_CHANNELS  VARCHAR(200)
);

CREATE INDEX IDX_ALERT_RULE_SERVER ON RX_ALERT_RULE (SERVER_ID);

-- ---------- 21. 告警事件 ----------
CREATE TABLE RX_ALERT_EVENT (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTANCE_ID  BIGINT,
    RULE_ID      BIGINT,
    LEVEL        VARCHAR(20),
    MESSAGE      TEXT,
    STATUS       VARCHAR(20),
    CREATED_TIME TIMESTAMP
);

CREATE INDEX IDX_ALERT_EVENT_INSTANCE ON RX_ALERT_EVENT (INSTANCE_ID);
CREATE INDEX IDX_ALERT_EVENT_RULE ON RX_ALERT_EVENT (RULE_ID);
CREATE INDEX IDX_ALERT_EVENT_STATUS_TIME ON RX_ALERT_EVENT (STATUS, CREATED_TIME);

-- ---------- 22. 配置表 ----------
CREATE TABLE RX_CONFIG (
    CONFIG_KEY   VARCHAR(100) PRIMARY KEY,
    CONFIG_VALUE CLOB,
    DESCRIPTION  TEXT
);

-- ---------- 23. 动态翻译 ----------
CREATE TABLE RX_I18N (
    I18N_KEY VARCHAR(100) NOT NULL,
    LANG     VARCHAR(10)  NOT NULL,
    TEXT     VARCHAR(500) NOT NULL,
    PRIMARY KEY (I18N_KEY, LANG)
);

-- ---------- 24. 文档管理 ----------
CREATE TABLE RX_DOC_TEMPLATE (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME         VARCHAR(100) NOT NULL,
    CATEGORY     VARCHAR(50),
    CONTENT      CLOB,
    CREATED_BY   VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    DOC_TYPE     VARCHAR(50) DEFAULT 'DOC'
);

CREATE TABLE RX_DOC (
    ID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEMPLATE_ID   BIGINT,
    TITLE         VARCHAR(200) NOT NULL,
    CONTENT       CLOB,
    VERSION       INT DEFAULT 1,
    STATUS        VARCHAR(20) DEFAULT 'DRAFT',
    REJECT_REASON VARCHAR(500),
    CREATED_BY    VARCHAR(50),
    UPDATED_BY    VARCHAR(50),
    APPROVED_BY   VARCHAR(50),
    APPROVED_TIME TIMESTAMP,
    CREATED_TIME  TIMESTAMP,
    UPDATED_TIME  TIMESTAMP,
    DELETED_TIME  TIMESTAMP,
    DOC_TYPE      VARCHAR(50) DEFAULT 'DOC'
);

CREATE INDEX IDX_DOC_VERSION ON RX_DOC_VERSION (DOC_ID);

CREATE TABLE RX_DOC_VERSION (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DOC_ID       BIGINT NOT NULL,
    VERSION      INT    NOT NULL,
    TITLE        VARCHAR(200),
    CONTENT      CLOB,
    OPERATOR     VARCHAR(50),
    CREATED_TIME TIMESTAMP
);

-- ---------- 25. 行政区划 ----------
CREATE TABLE RX_REGION (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE         VARCHAR(12)  NOT NULL,
    NAME         VARCHAR(64)  NOT NULL,
    LEVEL        SMALLINT     NOT NULL,
    PARENT_CODE  VARCHAR(12)  DEFAULT '' NOT NULL,
    PINYIN       VARCHAR(128),
    ABBREVIATION VARCHAR(32),
    LONGITUDE    DECIMAL(10,6),
    LATITUDE     DECIMAL(10,6),
    SORT         INT          DEFAULT 0 NOT NULL,
    STATUS       SMALLINT     DEFAULT 1 NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    UNIQUE (CODE)
);

CREATE INDEX IDX_REGION_PARENT ON RX_REGION (PARENT_CODE);
CREATE INDEX IDX_REGION_LEVEL ON RX_REGION (LEVEL);

-- ---------- 26. 日历事件 ----------
CREATE TABLE RX_CALENDAR_EVENT (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID      BIGINT       NOT NULL,
    TITLE        VARCHAR(128) NOT NULL,
    DESCRIPTION  VARCHAR(1000),
    EVENT_DATE   DATE         NOT NULL,
    START_TIME   TIME,
    END_TIME     TIME,
    EVENT_TYPE   VARCHAR(16)  DEFAULT 'other' NOT NULL,
    PRIORITY     SMALLINT     DEFAULT 1 NOT NULL,
    COLOR        VARCHAR(16),
    IS_ALL_DAY   SMALLINT     DEFAULT 1 NOT NULL,
    STATUS       SMALLINT     DEFAULT 1 NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP
);

CREATE INDEX IDX_CAL_USER_DATE ON RX_CALENDAR_EVENT (USER_ID, EVENT_DATE);

-- ---------- 27. Webhook ----------
CREATE TABLE RX_WEBHOOK (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME         VARCHAR(100) NOT NULL,
    URL          VARCHAR(500) NOT NULL,
    SECRET       VARCHAR(200),
    ENABLED      SMALLINT     DEFAULT 1 NOT NULL,
    DESCRIPTION  VARCHAR(255),
    CREATED_BY   VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    UNIQUE (NAME)
);

-- ---------- 28. Webhook 日志 ----------
CREATE TABLE RX_WEBHOOK_LOG (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WEBHOOK_ID   BIGINT,
    WEBHOOK_NAME VARCHAR(100),
    TITLE        VARCHAR(255),
    MESSAGE      TEXT,
    SUCCESS      SMALLINT     DEFAULT 0 NOT NULL,
    ATTEMPTS     INT          DEFAULT 0 NOT NULL,
    ERROR_MSG    VARCHAR(500),
    CREATED_TIME TIMESTAMP
);

CREATE INDEX IDX_WEBLOG_TIME ON RX_WEBHOOK_LOG (CREATED_TIME);
CREATE INDEX IDX_WEBLOG_WEBHOOK ON RX_WEBHOOK_LOG (WEBHOOK_ID);

-- ---------- 29. 站内通知 ----------
CREATE TABLE RX_NOTIFICATION (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME     VARCHAR(50)  NOT NULL,
    TYPE         VARCHAR(20)  DEFAULT 'SYSTEM' NOT NULL,
    TITLE        VARCHAR(255) NOT NULL,
    CONTENT      TEXT,
    READ_FLAG    SMALLINT     DEFAULT 0 NOT NULL,
    CREATED_TIME TIMESTAMP
);

CREATE INDEX IDX_NOTIF_USER ON RX_NOTIFICATION (USERNAME, READ_FLAG);
CREATE INDEX IDX_NOTIF_TIME ON RX_NOTIFICATION (CREATED_TIME);

-- ---------- 30. 通知公告 ----------
CREATE TABLE RX_NOTICE (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE        VARCHAR(200) NOT NULL,
    CONTENT      CLOB,
    STATUS       VARCHAR(20)  DEFAULT 'DRAFT',
    PUBLISHED_BY VARCHAR(50),
    CREATED_BY   VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    PUBLISHED_TIME TIMESTAMP
);

-- ---------- 31. 权限申请 ----------
CREATE TABLE RX_PERMISSION_REQUEST (
    ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME        VARCHAR(50)  NOT NULL,
    PERMISSION_CODE VARCHAR(100),
    MENU_IDS        VARCHAR(2000),
    MENU_NAMES      VARCHAR(2000),
    REASON          TEXT,
    STATUS          VARCHAR(20)  DEFAULT 'PENDING',
    REVIEWER        VARCHAR(50),
    REVIEW_TIME     TIMESTAMP,
    CREATED_TIME    TIMESTAMP
);

-- ---------- 32. IP 规则 ----------
CREATE TABLE RX_IP_RULE (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IP_ADDRESS   VARCHAR(50)  NOT NULL,
    RULE_TYPE    VARCHAR(10)  NOT NULL,
    DESCRIPTION  VARCHAR(255),
    ENABLED      SMALLINT     DEFAULT 1 NOT NULL,
    CREATED_BY   VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP
);

-- ---------- 33. 仪表盘组件 ----------
CREATE TABLE RX_DASHBOARD_WIDGET (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WIDGET_TYPE  VARCHAR(50)  NOT NULL,
    TITLE        VARCHAR(100),
    CONFIG       CLOB,
    SORT         INT          DEFAULT 0 NOT NULL,
    VISIBLE      SMALLINT     DEFAULT 1 NOT NULL,
    USERNAME     VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP
);

-- ---------- 34. 收藏 ----------
CREATE TABLE RX_FAVORITE (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME     VARCHAR(50)  NOT NULL,
    TITLE        VARCHAR(200) NOT NULL,
    PATH         VARCHAR(200) NOT NULL,
    ICON         VARCHAR(100),
    CREATED_TIME TIMESTAMP,
    UNIQUE (USERNAME, PATH)
);

-- ---------- 35. 数据字典 ----------
CREATE TABLE RX_DICT_TYPE (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE         VARCHAR(50)  NOT NULL,
    NAME         VARCHAR(100) NOT NULL,
    REMARK       VARCHAR(255),
    SORT         INT          DEFAULT 0 NOT NULL,
    STATUS       SMALLINT     DEFAULT 1 NOT NULL,
    CREATED_BY   VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    UNIQUE (CODE)
);

CREATE TABLE RX_DICT_ITEM (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TYPE_CODE    VARCHAR(50)  NOT NULL,
    ITEM_KEY     VARCHAR(50)  NOT NULL,
    ITEM_VALUE   VARCHAR(200) NOT NULL,
    SORT         INT          DEFAULT 0 NOT NULL,
    STATUS       SMALLINT     DEFAULT 1 NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    UNIQUE (TYPE_CODE, ITEM_KEY)
);

-- ---------- 36. 报表调度 ----------
CREATE TABLE RX_REPORT_SCHEDULE (
    ID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR(100) NOT NULL,
    REPORT_TYPE   VARCHAR(20)  NOT NULL,
    FORMAT        VARCHAR(10)  DEFAULT 'xlsx' NOT NULL,
    SERVER_ID     BIGINT,
    DAYS          INT          DEFAULT 7 NOT NULL,
    CRON_EXPR     VARCHAR(100) NOT NULL,
    RECIPIENTS    CLOB,
    ENABLED       SMALLINT     DEFAULT 1,
    STATUS        VARCHAR(20)  DEFAULT 'PENDING',
    LAST_RUN_TIME TIMESTAMP,
    LAST_RESULT   VARCHAR(500),
    CREATED_BY    VARCHAR(50),
    CREATED_TIME  TIMESTAMP,
    UPDATED_TIME  TIMESTAMP
);

CREATE TABLE RX_REPORT_SCHEDULE_HISTORY (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SCHEDULE_ID  BIGINT NOT NULL,
    RUN_TIME     TIMESTAMP NOT NULL,
    STATUS       VARCHAR(20),
    MESSAGE      VARCHAR(1000),
    FILE_BYTES   BIGINT DEFAULT 0,
    CREATED_TIME TIMESTAMP
);

CREATE INDEX IDX_REPORT_SCHEDULE_HISTORY ON RX_REPORT_SCHEDULE_HISTORY (SCHEDULE_ID, RUN_TIME);

-- ---------- 37. 作业 SLA ----------
CREATE TABLE RX_JOB_SLA (
    ID                    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_NAME              VARCHAR(64)  NOT NULL,
    SCHEDULE_NAME         VARCHAR(128),
    EXPECTED_DURATION_SEC INT          NOT NULL,
    DEVIATION_PERCENT     INT          DEFAULT 20 NOT NULL,
    ENABLED               SMALLINT     DEFAULT 1 NOT NULL,
    CREATED_TIME          TIMESTAMP,
    UPDATED_TIME          TIMESTAMP
);

CREATE INDEX IDX_JOB_SLA_JOB ON RX_JOB_SLA (JOB_NAME);

-- ---------- 38. 分布式锁 ----------
CREATE TABLE RX_DIST_LOCK (
    LOCK_KEY    VARCHAR(64)  NOT NULL,
    HOLDER      VARCHAR(64),
    ACQUIRED_AT TIMESTAMP,
    EXPIRES_AT  TIMESTAMP,
    PRIMARY KEY (LOCK_KEY)
);

INSERT INTO RX_DIST_LOCK (LOCK_KEY, HOLDER, ACQUIRED_AT, EXPIRES_AT)
VALUES ('rx_monitor_collector', NULL, NULL, NULL);

-- ---------- 39. JWT 吊销名单 ----------
CREATE TABLE RX_TOKEN_BLACKLIST (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JTI          VARCHAR(64)  NOT NULL,
    USERNAME     VARCHAR(64)  NOT NULL,
    EXPIRE_TIME  TIMESTAMP    NOT NULL,
    CREATED_TIME TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (JTI)
);

CREATE INDEX IDX_TOKEN_BLACKLIST_EXPIRE ON RX_TOKEN_BLACKLIST (EXPIRE_TIME);

-- ---------- 40. 源码/编译（仅 RXADMIN 中的元数据） ----------
CREATE TABLE RX_SOURCE_LIBRARY (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LIBRARY_NAME VARCHAR(100),
    DESCRIPTION  TEXT,
    SYSTEM_NAME  VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RX_SOURCE_FILE (
    ID        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LIBRARY   VARCHAR(100),
    FILE_NAME VARCHAR(100),
    TYPE      VARCHAR(50)
);

CREATE TABLE RX_SOURCE_MEMBER (
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LIBRARY     VARCHAR(100),
    SOURCE_FILE VARCHAR(100),
    MEMBER_NAME VARCHAR(100),
    SOURCE_TYPE VARCHAR(50)
);

CREATE TABLE RX_COMPILE_RECORD (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LIBRARY      VARCHAR(100),
    SOURCE_FILE  VARCHAR(100),
    MEMBER       VARCHAR(100),
    COMMAND      VARCHAR(100),
    STATUS       VARCHAR(20),
    MESSAGE      TEXT,
    OPERATOR     VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- ============================================================
-- 1. 角色（4 个固定角色）
-- ============================================================
INSERT INTO RX_ROLE (ROLE_CODE, ROLE_NAME, DESCRIPTION, SORT, STATUS) VALUES
('ADMIN',     '系统管理员', NULL, 0, 1),
('OPERATOR',  'IBM i 运维员', NULL, 0, 1),
('DEVELOPER', '开发人员', NULL, 0, 1),
('VIEWER',    '只读用户', NULL, 0, 1);

-- ============================================================
-- 2. 权限码（55 个，全部）
-- ============================================================
INSERT INTO RX_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE) VALUES
('JOB_VIEW', 'JOB_VIEW', 'SYSTEM'),
('JOB_END', 'JOB_END', 'SYSTEM'),
('MONITOR_VIEW', 'MONITOR_VIEW', 'SYSTEM'),
('USER_MANAGE', 'USER_MANAGE', 'SYSTEM'),
('SOURCE_VIEW', 'SOURCE_VIEW', 'SYSTEM'),
('COMPILE_EXECUTE', 'COMPILE_EXECUTE', 'SYSTEM'),
('QUERY_EXECUTE', 'QUERY_EXECUTE', 'SYSTEM'),
('AS400_MANAGE', 'AS400_MANAGE', 'SYSTEM'),
('OBJECT_VIEW', 'OBJECT_VIEW', 'SYSTEM'),
('SCHEDULE_VIEW', 'SCHEDULE_VIEW', 'SYSTEM'),
('SCHEDULE_MANAGE', 'SCHEDULE_MANAGE', 'SYSTEM'),
('SCRIPT_VIEW', 'SCRIPT_VIEW', 'SYSTEM'),
('SCRIPT_MANAGE', 'SCRIPT_MANAGE', 'SYSTEM'),
('IFS_VIEW', 'IFS_VIEW', 'SYSTEM'),
('SUBSYSTEM_VIEW', 'SUBSYSTEM_VIEW', 'SYSTEM'),
('SUBSYSTEM_MANAGE', 'SUBSYSTEM_MANAGE', 'SYSTEM'),
('EXECUTION_VIEW', 'EXECUTION_VIEW', 'SYSTEM'),
('PF_VIEW', 'PF_VIEW', 'SYSTEM'),
('AUDIT_VIEW', 'AUDIT_VIEW', 'SYSTEM'),
('HEALTH_VIEW', 'HEALTH_VIEW', 'SYSTEM'),
('TOPOLOGY_VIEW', 'TOPOLOGY_VIEW', 'SYSTEM'),
('REPORT_VIEW', 'REPORT_VIEW', 'SYSTEM'),
('REPORT_MANAGE', 'REPORT_MANAGE', 'SYSTEM'),
('DOC_VIEW', 'DOC_VIEW', 'SYSTEM'),
('DOC_MANAGE', 'DOC_MANAGE', 'SYSTEM'),
('DOC_APPROVE', 'DOC_APPROVE', 'SYSTEM'),
('MENU_MANAGE', 'MENU_MANAGE', 'SYSTEM'),
('REGION_VIEW', 'REGION_VIEW', 'SYSTEM'),
('REGION_MANAGE', 'REGION_MANAGE', 'SYSTEM'),
('CALENDAR_VIEW', 'CALENDAR_VIEW', 'SYSTEM'),
('CALENDAR_MANAGE', 'CALENDAR_MANAGE', 'SYSTEM'),
('ROLE_MANAGE', 'ROLE_MANAGE', 'SYSTEM'),
('SYS_CONFIG_MANAGE', 'SYS_CONFIG_MANAGE', 'SYSTEM'),
('I18N_MANAGE', 'I18N_MANAGE', 'SYSTEM'),
('SYS_CACHE_MANAGE', 'SYS_CACHE_MANAGE', 'SYSTEM'),
('SYS_TASK_MANAGE', 'SYS_TASK_MANAGE', 'SYSTEM'),
('SYS_IP_MANAGE', 'SYS_IP_MANAGE', 'SYSTEM'),
('WEBHOOK_MANAGE', 'WEBHOOK_MANAGE', 'SYSTEM'),
('NOTICE_MANAGE', 'NOTICE_MANAGE', 'SYSTEM'),
('SYS_PERMISSION_REQUEST', 'SYS_PERMISSION_REQUEST', 'SYSTEM'),
('NOTIFICATION_MANAGE', 'NOTIFICATION_MANAGE', 'SYSTEM'),
('DICT_MANAGE', 'DICT_MANAGE', 'SYSTEM'),
('PERMISSION_MANAGE', 'PERMISSION_MANAGE', 'SYSTEM'),
('ALERT_MANAGE', 'ALERT_MANAGE', 'SYSTEM'),
('MSGF_VIEW', 'MSGF_VIEW', 'SYSTEM'),
('MSGF_ADD', 'MSGF_ADD', 'SYSTEM'),
('MSGF_EDIT', 'MSGF_EDIT', 'SYSTEM'),
('MSGF_DELETE', 'MSGF_DELETE', 'SYSTEM'),
('SYSVAL_VIEW', 'SYSVAL_VIEW', 'SYSTEM'),
('SYSVAL_EDIT', 'SYSVAL_EDIT', 'SYSTEM'),
('SLA_VIEW', 'SLA_VIEW', 'SYSTEM'),
('SLA_EDIT', 'SLA_EDIT', 'SYSTEM'),
('SLA_MANAGE', 'SLA_MANAGE', 'SYSTEM'),
('INSPECT_VIEW', 'INSPECT_VIEW', 'SYSTEM'),
('IFS_MANAGE', 'IFS_MANAGE', 'SYSTEM');

-- ============================================================
-- 3. 角色授权（ADMIN 全部权限）
-- ============================================================
INSERT INTO RX_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT R.ID, P.ID FROM RX_ROLE R, RX_PERMISSION P WHERE R.ROLE_CODE = 'ADMIN';

-- ============================================================
-- 4. 菜单树（先目录，再叶子，最后按钮/Tab）
-- ============================================================

-- 4.1 目录（menu_type=1，parent_id=NULL）
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME) VALUES
(NULL, '总览', 2, 'dashboard', '/dashboard', 'Odometer', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME) VALUES
(NULL, '监控中心', 1, 'groupMonitor', '/group-monitor', 'Monitor', 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME) VALUES
(NULL, '作业与任务', 1, 'groupJob', '/group-job', 'Suitcase', 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME) VALUES
(NULL, '数据与对象', 1, 'groupData', '/group-data', 'Box', 4, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME) VALUES
(NULL, '报表与文档', 1, 'groupReport', '/group-report', 'DataAnalysis', 5, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME) VALUES
(NULL, '系统管理', 1, 'system', '/system', 'Setting', 6, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME) VALUES
(NULL, '工具', 1, 'groupTools', '/group-tools', 'Tools', 7, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME) VALUES
(NULL, '业务管理', 1, 'biz', '/group-biz', 'Briefcase', 8, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME) VALUES
(NULL, '发布与代码', 1, 'groupRelease', '/group-release', 'Promotion', 90, 1, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 4.2 监控中心叶子（parent_id = groupMonitor.id）
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '监控中心', 2, 'monitor', '/monitor', 'views/Monitor.vue', 'MONITOR_VIEW', 'Monitor', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupMonitor' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '健康巡检', 2, 'health', '/health', 'views/health/index.vue', 'HEALTH_VIEW', 'FirstAidKit', 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupMonitor' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '服务器管理', 2, 'assets', '/assets', 'views/assets/index.vue', NULL, 'Coin', 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupMonitor' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '告警规则', 2, 'alertRules', '/monitor/alert-rules', 'views/monitor/alertRules/index.vue', 'MONITOR_VIEW', 'fa-solid fa-bell', 4, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupMonitor' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '服务器对比', 2, 'serverCompare', '/server-compare', 'views/monitor/serverCompare/index.vue', 'MONITOR_VIEW', 'fa-solid fa-scale-balanced', 5, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupMonitor' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '巡检报告', 2, 'inspection', '/inspection', 'views/monitor/inspection/index.vue', 'MONITOR_VIEW', 'fa-solid fa-clipboard-check', 6, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupMonitor' AND MENU_TYPE = 1;

-- 4.3 作业与任务叶子
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, 'Job 中心', 2, 'jobs', '/jobs', 'views/job/index.vue', 'JOB_VIEW', 'Suitcase', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupJob' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '作业调度', 2, 'schedules', '/schedules', 'views/schedule/index.vue', 'SCHEDULE_VIEW', 'AlarmClock', 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupJob' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '命令脚本', 2, 'scripts', '/scripts', 'views/scripts/index.vue', 'SCRIPT_VIEW', 'Files', 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupJob' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '执行审计', 2, 'executions', '/executions', 'views/executions/index.vue', 'EXECUTION_VIEW', 'Document', 4, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupJob' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '作业SLA', 2, 'jobSla', '/job-sla', 'views/job/sla/index.vue', 'JOB_VIEW', 'fa-solid fa-stopwatch', 5, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupJob' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '作业依赖图', 2, 'jobDependency', '/job-dependency', 'views/job/dependency/index.vue', 'JOB_VIEW', 'fa-solid fa-diagram-project', 6, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupJob' AND MENU_TYPE = 1;

-- 4.4 数据与对象叶子
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '数据查询', 2, 'query', '/query', 'views/query/index.vue', 'QUERY_EXECUTE', 'Search', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupData' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '对象搜索', 2, 'objects', '/objects', 'views/objects/index.vue', 'OBJECT_VIEW', 'Box', 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupData' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, 'IFS 文件', 2, 'ifs', '/ifs', 'views/ifs/index.vue', 'IFS_VIEW', 'FolderOpened', 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupData' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '系统服务', 2, 'subsystems', '/subsystems', 'views/subsystems/index.vue', 'SUBSYSTEM_VIEW', 'Setting', 4, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupData' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, 'PF 文件浏览', 2, 'pf', '/pf', 'views/pf/index.vue', 'PF_VIEW', 'Tickets', 5, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupData' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '拓扑分析', 2, 'topology', '/topology', 'views/topology/index.vue', 'TOPOLOGY_VIEW', 'Share', 6, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupData' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '文件字段', 2, 'tableFields', '/table-fields', 'views/data/tableFields/index.vue', 'QUERY_EXECUTE', 'fa-solid fa-file-lines', 7, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupData' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '消息文件', 2, 'messageFiles', '/message-files', 'views/data/messageFiles/index.vue', 'MSGF_VIEW', 'fa-solid fa-envelope-open-text', 8, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupData' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '系统值', 2, 'sysvals', '/sysvals', 'views/data/sysvals/index.vue', 'SYSVAL_VIEW', 'fa-solid fa-gears', 9, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupData' AND MENU_TYPE = 1;

-- 4.5 报表与文档叶子
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '报表中心', 2, 'reports', '/reports', 'views/report/index.vue', 'REPORT_VIEW', 'DataAnalysis', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupReport' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '文档管理', 2, 'docs', '/docs', 'views/docs/index.vue', 'DOC_VIEW', 'Collection', 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupReport' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '审计日志', 2, 'audit', '/audit', 'views/audit/index.vue', 'AUDIT_VIEW', 'Notebook', 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupReport' AND MENU_TYPE = 1;

-- 4.6 系统管理叶子
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '用户管理', 2, 'users', '/users', 'views/system/Users.vue', 'USER_MANAGE', 'User', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '角色管理', 2, 'roles', '/roles', 'views/system/roles/index.vue', 'ROLE_MANAGE', 'UserFilled', 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '菜单管理', 2, 'menus', '/menus', 'views/system/menus/index.vue', 'MENU_MANAGE', 'Menu', 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '系统配置', 2, 'config', '/system/config', 'views/system/config/index.vue', 'SYS_CONFIG_MANAGE', 'fa-solid fa-sliders', 4, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '翻译管理', 2, 'i18n', '/system/i18n', 'views/system/i18n/index.vue', 'I18N_MANAGE', 'fa-solid fa-globe', 5, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '登录日志', 2, 'loginLog', '/system/login-log', 'views/system/loginLog/index.vue', 'AUDIT_VIEW', 'fa-solid fa-clock-rotate-left', 6, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '缓存管理', 2, 'cache', '/system/cache', 'views/system/cache/index.vue', 'SYS_CACHE_MANAGE', 'fa-solid fa-bolt', 7, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '定时任务', 2, 'tasks', '/system/tasks', 'views/system/tasks/index.vue', 'SYS_TASK_MANAGE', 'fa-solid fa-clock', 8, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, 'IP 黑白名单', 2, 'ipRules', '/system/ip-rules', 'views/system/ipRules/index.vue', 'SYS_IP_MANAGE', 'fa-solid fa-shield', 9, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, 'Webhook 管理', 2, 'webhooks', '/system/webhooks', 'views/system/webhooks/index.vue', 'WEBHOOK_MANAGE', 'fa-solid fa-envelope', 10, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '权限申请', 2, 'permissionRequest', '/system/permission-request', 'views/system/permissionRequest/index.vue', 'SYS_PERMISSION_REQUEST', 'fa-solid fa-key', 11, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '通知公告', 2, 'notices', '/system/notices', 'views/system/notice/index.vue', 'NOTICE_MANAGE', 'fa-solid fa-bullhorn', 12, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '字典管理', 2, 'dict', '/system/dict', 'views/system/dict/index.vue', 'DICT_MANAGE', 'fa-solid fa-book', 13, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '权限码管理', 2, 'permissions', '/system/permissions', 'views/system/permissions/index.vue', 'PERMISSION_MANAGE', 'fa-solid fa-key', 14, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '参数维护', 2, 'params', '/system/params', 'views/system/params/index.vue', NULL, 'fa-solid fa-gears', 15, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;

-- 4.7 工具叶子
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '区域管理', 2, 'region', '/region', 'views/tool/region/index.vue', 'REGION_VIEW', 'Location', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupTools' AND MENU_TYPE = 1;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '日历', 2, 'calendar', '/calendar', 'views/calendar/index.vue', 'CALENDAR_VIEW', 'Calendar', 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupTools' AND MENU_TYPE = 1;

-- 4.8 业务管理叶子
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '业务数据浏览', 2, 'bizData', '/biz-data', 'views/biz/data/index.vue', 'QUERY_EXECUTE', 'fa-solid fa-table', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'biz' AND MENU_TYPE = 1;

-- 4.9 发布与代码叶子（停用组）
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PATH, COMPONENT, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '源代码', 2, 'source', '/source', 'views/Source.vue', NULL, 'FolderOpened', 1, 1, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'groupRelease' AND MENU_TYPE = 1;

-- 4.10 按钮（menu_type=3）
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, 'SLA管理', 3, 'slaManage', 'SLA_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'jobSla' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '新增消息', 3, 'msgfAdd', 'MSGF_ADD', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'messageFiles' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '修改消息', 3, 'msgfEdit', 'MSGF_EDIT', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'messageFiles' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '删除消息', 3, 'msgfDelete', 'MSGF_DELETE', NULL, 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'messageFiles' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '修改系统值', 3, 'sysvalEdit', 'SYSVAL_EDIT', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'sysvals' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '告警规则管理', 3, 'alertRuleManage', 'ALERT_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'alertRules' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '定时报表管理', 3, 'reportScheduleManage', 'REPORT_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'reports' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '作业控制', 3, 'jobControl', 'JOB_END', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'jobs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '消息应答', 3, 'jobReply', 'JOB_END', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'jobs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '启停子系统', 3, 'subsystemControl', 'SUBSYSTEM_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'subsystems' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '脚本管理', 3, 'scriptManage', 'SCRIPT_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'scripts' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '调度管理', 3, 'scheduleManage', 'SCHEDULE_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'schedules' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '文档管理', 3, 'docManage', 'DOC_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'docs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '文档审批', 3, 'docApprove', 'DOC_APPROVE', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'docs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '日历管理', 3, 'calendarManage', 'CALENDAR_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'calendar' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '区域管理', 3, 'regionManage', 'REGION_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'region' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '上传文件', 3, 'ifsUpload', 'IFS_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'ifs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '下载文件', 3, 'ifsDownload', 'IFS_MANAGE', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'ifs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '新建目录', 3, 'ifsMkdir', 'IFS_MANAGE', NULL, 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'ifs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '删除文件', 3, 'ifsDelete', 'IFS_MANAGE', NULL, 4, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'ifs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '编译执行', 3, 'compileExecute', 'COMPILE_EXECUTE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'source' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '服务器管理', 3, 'assetsManage', 'AS400_MANAGE', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'assets' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, ICON, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '通知管理', 3, 'notificationManage', 'NOTIFICATION_MANAGE', 'fa-solid fa-bell', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'system' AND MENU_TYPE = 1;

-- 4.11 Tab（menu_type=4）
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '审批管理', 4, 'permissionRequestReview', 'SYS_PERMISSION_REQUEST', 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'permissionRequest' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '作业', 4, 'jobsTab', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'jobs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '队列', 4, 'queuesTab', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'jobs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '输出', 4, 'spoolTab', NULL, 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'jobs' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '用户', 4, 'usersTab', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'users' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '登录安全', 4, 'securityTab', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'users' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '配置', 4, 'configTab', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'webhooks' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '日志', 4, 'logTab', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'webhooks' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '引用入', 4, 'refIn', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'objects' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '引用出', 4, 'refOut', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'objects' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '对象权限', 4, 'authorities', NULL, 3, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'objects' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '引用入', 4, 'refIn', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'topology' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '引用出', 4, 'refOut', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'topology' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '手动导出', 4, 'reportManualTab', NULL, 1, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'reports' AND MENU_TYPE = 2;
INSERT INTO RX_MENU (PARENT_ID, MENU_NAME, MENU_TYPE, TITLE, PERMS, SORT, VISIBLE, STATUS, ADMIN_ONLY, CREATED_TIME, UPDATED_TIME)
SELECT ID, '定时任务', 4, 'reportScheduleTab', NULL, 2, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM RX_MENU WHERE TITLE = 'reports' AND MENU_TYPE = 2;

-- ============================================================
-- 5. 角色-菜单授权（ADMIN 全部启用菜单）
-- ============================================================
INSERT INTO RX_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT R.ID, M.ID FROM RX_ROLE R, RX_MENU M
WHERE R.ROLE_CODE = 'ADMIN' AND M.STATUS = 1;

-- OPERATOR 角色菜单
INSERT INTO RX_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT R.ID, M.ID FROM RX_ROLE R, RX_MENU M
WHERE R.ROLE_CODE = 'OPERATOR' AND M.STATUS = 1 AND M.TITLE IN (
    'dashboard', 'groupMonitor', 'monitor', 'health', 'assets',
    'groupJob', 'jobs', 'schedules', 'scripts', 'executions',
    'groupData', 'query', 'objects', 'ifs', 'subsystems', 'pf', 'topology',
    'groupReport', 'reports', 'docs', 'audit',
    'groupTools', 'region', 'calendar',
    'loginLog', 'permissionRequest', 'biz', 'bizData', 'tableFields',
    'jobControl', 'jobReply', 'subsystemControl', 'scriptManage', 'scheduleManage',
    'messageFiles', 'sysvals', 'serverCompare', 'inspection', 'jobSla', 'jobDependency',
    'msgfAdd', 'msgfEdit', 'msgfDelete', 'sysvalEdit', 'slaManage'
);

-- DEVELOPER 角色菜单
INSERT INTO RX_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT R.ID, M.ID FROM RX_ROLE R, RX_MENU M
WHERE R.ROLE_CODE = 'DEVELOPER' AND M.STATUS = 1 AND M.TITLE IN (
    'dashboard', 'groupJob', 'schedules', 'scripts',
    'groupData', 'query', 'objects', 'pf',
    'groupReport', 'reports', 'docs',
    'groupTools', 'region', 'calendar',
    'permissionRequest', 'biz', 'bizData', 'tableFields',
    'scriptManage', 'scheduleManage',
    'messageFiles', 'sysvals', 'serverCompare', 'inspection', 'jobSla', 'jobDependency',
    'msgfAdd', 'msgfEdit', 'msgfDelete', 'slaManage'
);

-- VIEWER 角色菜单
INSERT INTO RX_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT R.ID, M.ID FROM RX_ROLE R, RX_MENU M
WHERE R.ROLE_CODE = 'VIEWER' AND M.STATUS = 1 AND M.TITLE IN (
    'dashboard', 'groupMonitor', 'monitor', 'health', 'assets',
    'groupJob', 'jobs', 'schedules', 'scripts', 'executions',
    'groupData', 'query', 'objects', 'ifs', 'subsystems', 'pf', 'topology',
    'groupReport', 'reports', 'docs', 'audit',
    'groupTools', 'region', 'calendar',
    'biz', 'bizData', 'tableFields', 'permissionRequest',
    'messageFiles', 'sysvals', 'serverCompare', 'inspection', 'jobSla', 'jobDependency'
);

-- ============================================================
-- 6. 行政区划（全量，来自 V10，23 省）
-- ============================================================
-- 注意：DB2 for i 不支持 MySQL 的 INSERT ... VALUES (...) 批量语法，
-- 需逐行插入。以下仅列出省级汇总，完整数据请参考 V10 迁移文件。
-- 实际部署时建议通过 CSV 导入（ACS 上传 + IMPORT 命令）。

-- 省级（level=1）
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('450000', '广西壮族自治区', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('460000', '海南省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('500000', '重庆市', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('510000', '四川省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('520000', '贵州省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('530000', '云南省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('540000', '西藏自治区', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('610000', '陕西省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('620000', '甘肃省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('630000', '青海省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('640000', '宁夏回族自治区', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('650000', '新疆维吾尔自治区', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('110000', '北京市', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('120000', '天津市', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('130000', '河北省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('140000', '山西省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('150000', '内蒙古自治区', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('210000', '辽宁省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('220000', '吉林省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('230000', '黑龙江省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('310000', '上海市', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('320000', '江苏省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('330000', '浙江省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('340000', '安徽省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('350000', '福建省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('360000', '江西省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('370000', '山东省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('410000', '河南省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('420000', '湖北省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('430000', '湖南省', 1, '', 1);
INSERT INTO RX_REGION (CODE, NAME, LEVEL, PARENT_CODE, STATUS) VALUES ('440000', '广东省', 1, '', 1);

-- 市/区县完整数据（2589 条，含 31 省 + 全部市/区县）
-- 完整 CSV 文件：docs/region_data.csv
-- 导入方式：通过 ACS 上传 CSV 后执行 IMPORT 命令
-- IMPORT FROM /QOpenSys/rxas400/region_data.csv OF DEL INSERT INTO RXADMIN.RX_REGION
-- CSV 格式：CODE,NAME,LEVEL,PARENT_CODE,STATUS

-- ============================================================
-- 7. 配置表（默认配置，来自 V1 + V48）
-- ============================================================
INSERT INTO RX_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES
('monitor.interval', '10', '监控采集间隔（秒）'),
('login.max.attempts', '5', '登录最大失败次数'),
('login.lock.minutes', '30', '登录锁定时间（分钟）'),
('as400.login.groupRoleMapping', '{"GRPADM":"ADMIN","GRPDEV":"DEVELOPER","GRPOPR":"OPERATOR"}', 'AS400 组 profile → 平台角色映射（JSON）'),
('alert.webhook.url', '', '告警 Webhook 推送地址（空=不推送）'),
('alert.webhook.lang', 'zh-CN', 'Webhook/邮件通知语言（zh-CN=中文，en-US=英文）');

-- ============================================================
-- 8. 动态翻译（基础）
-- ============================================================
INSERT INTO RX_I18N (I18N_KEY, LANG, TEXT) VALUES
('banner.welcome', 'zh-CN', '欢迎使用 RXAS400 运维平台'),
('banner.welcome', 'en-US', 'Welcome to RXAS400 Operation Platform'),
('banner.health', 'zh-CN', '平台运行健康'),
('banner.health', 'en-US', 'Platform is healthy');

-- ============================================================
-- 9. 默认管理员用户（admin / admin123，BCrypt 加密）
-- ============================================================
-- BCrypt hash of 'admin123': $2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi
INSERT INTO RX_USER (USERNAME, PASSWORD, EMAIL, STATUS, CREATED_BY, CREATED_TIME, UPDATED_TIME)
VALUES ('admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', 'admin@rxas400.local', 'ACTIVE', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- admin 关联 ADMIN 角色
INSERT INTO RX_USER_ROLE (USER_ID, ROLE_ID)
SELECT U.ID, R.ID FROM RX_USER U, RX_ROLE R WHERE U.USERNAME = 'admin' AND R.ROLE_CODE = 'ADMIN';

-- ============================================================
-- 10. 数据字典（来自 V16）
-- ============================================================
INSERT INTO RX_DICT_TYPE (CODE, NAME, REMARK, SORT, STATUS, CREATED_TIME, UPDATED_TIME)
VALUES ('job_status', '作业状态', 'Job 中心活动作业状态', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_DICT_ITEM (TYPE_CODE, ITEM_KEY, ITEM_VALUE, SORT, STATUS, CREATED_TIME, UPDATED_TIME)
VALUES ('job_status', 'RUN', '运行中', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_DICT_ITEM (TYPE_CODE, ITEM_KEY, ITEM_VALUE, SORT, STATUS, CREATED_TIME, UPDATED_TIME)
VALUES ('job_status', 'MSGW', '等待消息', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_DICT_ITEM (TYPE_CODE, ITEM_KEY, ITEM_VALUE, SORT, STATUS, CREATED_TIME, UPDATED_TIME)
VALUES ('job_status', 'HELD', '已挂起', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_DICT_ITEM (TYPE_CODE, ITEM_KEY, ITEM_VALUE, SORT, STATUS, CREATED_TIME, UPDATED_TIME)
VALUES ('job_status', 'LCKW', '死锁等待', 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_DICT_TYPE (CODE, NAME, REMARK, SORT, STATUS, CREATED_TIME, UPDATED_TIME)
VALUES ('server_env', '服务器环境', 'AS400 服务器环境标签', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_DICT_ITEM (TYPE_CODE, ITEM_KEY, ITEM_VALUE, SORT, STATUS, CREATED_TIME, UPDATED_TIME)
VALUES ('server_env', 'PROD', '生产', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_DICT_ITEM (TYPE_CODE, ITEM_KEY, ITEM_VALUE, SORT, STATUS, CREATED_TIME, UPDATED_TIME)
VALUES ('server_env', 'TEST', '测试', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_DICT_ITEM (TYPE_CODE, ITEM_KEY, ITEM_VALUE, SORT, STATUS, CREATED_TIME, UPDATED_TIME)
VALUES ('server_env', 'DEV', '开发', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- 11. 文档模板（来自 V48）
-- ============================================================
INSERT INTO RX_DOC_TEMPLATE (NAME, CATEGORY, CONTENT, CREATED_BY, CREATED_TIME, UPDATED_TIME)
VALUES ('运维变更单', '变更管理', '# ${title}

## 一、变更内容

## 二、变更原因

## 三、影响范围

## 四、实施步骤

## 五、回退方案

## 六、验证清单

- [ ] 变更前备份
- [ ] 实施完成
- [ ] 业务验证通过
', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RX_DOC_TEMPLATE (NAME, CATEGORY, CONTENT, CREATED_BY, CREATED_TIME, UPDATED_TIME)
VALUES ('运维值班记录', '日常运维', '# ${title}

- 值班人：
- 日期：

## 检查项
- [ ] 作业状态无 MSGW
- [ ] 磁盘使用率正常
- [ ] 备份任务成功

## 事件记录

## 交接事项
', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- 12. 分布式锁初始行
-- ============================================================
INSERT INTO RX_DIST_LOCK (LOCK_KEY, HOLDER, ACQUIRED_AT, EXPIRES_AT)
VALUES ('rx_monitor_collector', NULL, NULL, NULL);
-- 检查表数量（应为 40 张）
SELECT COUNT(*) FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = 'RXADMIN' AND TABLE_TYPE = 'BASE TABLE';

-- 检查角色
SELECT * FROM RXADMIN.RX_ROLE;

-- 检查菜单数量（应为 90 条）
SELECT COUNT(*) FROM RXADMIN.RX_MENU;

-- 检查权限数量（应为 55 条）
SELECT COUNT(*) FROM RXADMIN.RX_PERMISSION;

-- 检查行政区划（省级应为 31 条）
SELECT COUNT(*) FROM RXADMIN.RX_REGION WHERE LEVEL = 1;

-- 检查管理员用户
SELECT USERNAME, STATUS FROM RXADMIN.RX_USER WHERE USERNAME = 'admin';
