import type { RouteRecordRaw } from 'vue-router'

export default [
  {
    path: 'bpcs-order',
    name: 'BpcsOrder',
    component: () => import('@/views/bpcs/order/index.vue'),
    meta: { title: 'menu.bpcsOrder', cached: true },
  },
  {
    path: 'bpcs-customer',
    name: 'BpcsCustomer',
    component: () => import('@/views/bpcs/customer/index.vue'),
    meta: { title: 'menu.bpcsCustomer', cached: true },
  },
  {
    path: 'bpcs-inventory',
    name: 'BpcsInventory',
    component: () => import('@/views/bpcs/inventory/index.vue'),
    meta: { title: 'menu.bpcsInventory', cached: true },
  },
  {
    path: 'bpcs-shipping',
    name: 'BpcsShipping',
    component: () => import('@/views/bpcs/shipping/index.vue'),
    meta: { title: 'menu.bpcsShipping', cached: true },
  },
  {
    path: 'bpcs-invoice',
    name: 'BpcsInvoice',
    component: () => import('@/views/bpcs/invoice/index.vue'),
    meta: { title: 'menu.bpcsInvoice', cached: true },
  },
  {
    path: 'bpcs-sales',
    name: 'BpcsSales',
    component: () => import('@/views/bpcs/sales/index.vue'),
    meta: { title: 'menu.bpcsSales', cached: true },
  },
  {
    path: 'bpcs-purchase',
    name: 'BpcsPurchase',
    component: () => import('@/views/bpcs/purchase/index.vue'),
    meta: { title: 'menu.bpcsPurchase', cached: true },
  },
  {
    path: 'bpcs-item',
    name: 'BpcsItem',
    component: () => import('@/views/bpcs/item/index.vue'),
    meta: { title: 'menu.bpcsItem', cached: true },
  },
  {
    path: 'bpcs-order-list',
    name: 'BpcsOrderList',
    component: () => import('@/views/bpcs/orderList/index.vue'),
    meta: { title: 'menu.bpcsOrderList', cached: true },
  },
  {
    path: 'bpcs-inventory-alert',
    name: 'BpcsInventoryAlert',
    component: () => import('@/views/bpcs/inventoryAlert/index.vue'),
    meta: { title: 'menu.bpcsInventoryAlert', cached: true },
  },
  {
    path: 'bpcs-sales-analysis',
    name: 'BpcsSalesAnalysis',
    component: () => import('@/views/bpcs/salesAnalysis/index.vue'),
    meta: { title: 'menu.bpcsSalesAnalysis', cached: true },
  },
  {
    path: 'bpcs-inventory-history',
    name: 'BpcsInventoryHistory',
    component: () => import('@/views/bpcs/inventoryHistory/index.vue'),
    meta: { title: 'menu.bpcsInventoryHistory', cached: true },
  },
  {
    path: 'bpcs-purchase-receiving',
    name: 'BpcsPurchaseReceiving',
    component: () => import('@/views/bpcs/purchaseReceiving/index.vue'),
    meta: { title: 'menu.bpcsPurchaseReceiving', cached: true },
  },
  {
    path: 'bpcs-shipping-list',
    name: 'BpcsShippingList',
    component: () => import('@/views/bpcs/shippingList/index.vue'),
    meta: { title: 'menu.bpcsShippingList', cached: true },
  },
  {
    path: 'bpcs-abc-analysis',
    name: 'BpcsAbcAnalysis',
    component: () => import('@/views/bpcs/abcAnalysis/index.vue'),
    meta: { title: 'menu.bpcsAbcAnalysis', cached: true },
  },
  {
    path: 'bpcs-supplier-perf',
    name: 'BpcsSupplierPerf',
    component: () => import('@/views/bpcs/supplierPerf/index.vue'),
    meta: { title: 'menu.bpcsSupplierPerf', cached: true },
  },
  {
    path: 'bpcs-kpi',
    name: 'BpcsKpi',
    component: () => import('@/views/bpcs/kpi/index.vue'),
    meta: { title: 'menu.bpcsKpi', cached: true },
  },
  {
    path: 'bpcs-order-tracking',
    name: 'BpcsOrderTracking',
    component: () => import('@/views/bpcs/orderTracking/index.vue'),
    meta: { title: 'menu.bpcsOrderTracking', cached: true },
  },
  {
    path: 'bpcs-abc-xyz',
    name: 'BpcsAbcXyz',
    component: () => import('@/views/bpcs/abcXyz/index.vue'),
    meta: { title: 'menu.bpcsAbcXyz', cached: true },
  },
  {
    path: 'bpcs-customer-overview',
    name: 'BpcsCustomerOverview',
    component: () => import('@/views/bpcs/customerOverview/index.vue'),
    meta: { title: 'menu.bpcsCustomerOverview', cached: true },
  },
  {
    path: 'bpcs-cycle-count',
    name: 'BpcsCycleCount',
    component: () => import('@/views/bpcs/cycleCount/index.vue'),
    meta: { title: 'menu.bpcsCycleCount', cached: true },
  },
  {
    path: 'bpcs-order-analytics',
    name: 'BpcsOrderAnalytics',
    component: () => import('@/views/bpcs/orderAnalytics/index.vue'),
    meta: { title: 'menu.bpcsOrderAnalytics', cached: true },
  },
  {
    path: 'bpcs-order-detail',
    name: 'BpcsOrderDetail',
    component: () => import('@/views/bpcs/orderDetail/index.vue'),
    meta: { title: 'menu.bpcsOrderDetail', cached: true },
  },
  {
    path: 'bpcs-forecast',
    name: 'BpcsForecast',
    component: () => import('@/views/bpcs/forecast/index.vue'),
    meta: { title: 'menu.bpcsForecast', cached: true },
  },
  {
    path: 'bpcs-anomaly',
    name: 'BpcsAnomaly',
    component: () => import('@/views/bpcs/anomaly/index.vue'),
    meta: { title: 'menu.bpcsAnomaly', cached: true },
  },
  {
    path: 'bpcs-bom',
    name: 'BpcsBom',
    component: () => import('@/views/bpcs/bom/index.vue'),
    meta: { title: 'menu.bpcsBom', cached: true },
  },
  {
    path: 'bpcs-shipment-mgmt',
    name: 'BpcsShipmentMgmt',
    component: () => import('@/views/bpcs/shipmentMgmt/index.vue'),
    meta: { title: 'menu.bpcsShipmentMgmt', cached: true },
  },
  {
    path: 'bpcs-rcmx',
    name: 'BpcsRcmx',
    component: () => import('@/views/bpcs/rcmx/index.vue'),
    meta: { title: 'menu.bpcsRcmx', cached: true },
  },
  {
    path: 'bpcs-wabp',
    name: 'BpcsWabp',
    component: () => import('@/views/bpcs/wabp/index.vue'),
    meta: { title: 'menu.bpcsWabp', cached: true },
  },
  {
    path: 'bpcs-location-inv',
    name: 'BpcsLocationInv',
    component: () => import('@/views/bpcs/locationInv/index.vue'),
    meta: { title: 'menu.bpcsLocationInv', cached: true },
  },
  {
    path: 'bpcs-replenishment',
    name: 'BpcsReplenishment',
    component: () => import('@/views/bpcs/replenishment/index.vue'),
    meta: { title: 'menu.bpcsReplenishment', cached: true },
  },
  {
    path: 'bpcs-alert-engine',
    name: 'BpcsAlertEngine',
    component: () => import('@/views/bpcs/alertEngine/index.vue'),
    meta: { title: 'menu.bpcsAlertEngine', cached: true },
  },
  {
    path: 'bpcs-stock-value',
    name: 'BpcsStockValue',
    component: () => import('@/views/bpcs/stockValue/index.vue'),
    meta: { title: 'menu.bpcsStockValue', cached: true },
  },
  {
    path: 'bpcs-supplier-score',
    name: 'BpcsSupplierScore',
    component: () => import('@/views/bpcs/supplierScore/index.vue'),
    meta: { title: 'menu.bpcsSupplierScore', cached: true },
  },
  {
    path: 'bpcs-po-lifecycle',
    name: 'BpcsPoLifecycle',
    component: () => import('@/views/bpcs/poLifecycle/index.vue'),
    meta: { title: 'menu.bpcsPoLifecycle', cached: true },
  },
  {
    path: 'bpcs-credit-hold',
    name: 'BpcsCreditHold',
    component: () => import('@/views/bpcs/creditHold/index.vue'),
    meta: { title: 'menu.bpcsCreditHold', cached: true },
  },
  {
    path: 'bpcs-kanban',
    name: 'BpcsKanban',
    component: () => import('@/views/bpcs/kanban/index.vue'),
    meta: { title: 'menu.bpcsKanban', cached: true },
  },
  {
    path: 'bpcs-transport-dashboard',
    name: 'BpcsTransportDashboard',
    component: () => import('@/views/bpcs/transportDashboard/index.vue'),
    meta: { title: 'menu.bpcsTransportDashboard', cached: true },
  },
  {
    path: 'bpcs-order-template',
    name: 'BpcsOrderTemplate',
    component: () => import('@/views/bpcs/orderTemplate/index.vue'),
    meta: { title: 'menu.bpcsOrderTemplate', cached: true },
  },
  {
    path: 'bpcs-order-copy',
    name: 'BpcsOrderCopy',
    component: () => import('@/views/bpcs/orderCopy/index.vue'),
    meta: { title: 'menu.bpcsOrderCopy', cached: true },
  },
  {
    path: 'bpcs-order-change',
    name: 'BpcsOrderChange',
    component: () => import('@/views/bpcs/orderChange/index.vue'),
    meta: { title: 'menu.bpcsOrderChange', cached: true },
  },
  {
    path: 'bpcs-order-report',
    name: 'BpcsOrderReport',
    component: () => import('@/views/bpcs/orderReport/index.vue'),
    meta: { title: 'menu.bpcsOrderReport', cached: true },
  },
  {
    path: 'bpcs-rma',
    name: 'BpcsRma',
    component: () => import('@/views/bpcs/rma/index.vue'),
    meta: { title: 'menu.bpcsRma', cached: true },
  },
  {
    path: 'bpcs-order-schedule',
    name: 'BpcsOrderSchedule',
    component: () => import('@/views/bpcs/orderSchedule/index.vue'),
    meta: { title: 'menu.bpcsOrderSchedule', cached: true },
  },
  {
    path: 'bpcs-freight-cost',
    name: 'BpcsFreightCost',
    component: () => import('@/views/bpcs/freightCost/index.vue'),
    meta: { title: 'menu.bpcsFreightCost', cached: true },
  },
  {
    path: 'bpcs-inventory-sim',
    name: 'BpcsInventorySim',
    component: () => import('@/views/bpcs/inventorySim/index.vue'),
    meta: { title: 'menu.bpcsInventorySim', cached: true },
  },
  {
    path: 'bpcs-order-collab',
    name: 'BpcsOrderCollab',
    component: () => import('@/views/bpcs/orderCollab/index.vue'),
    meta: { title: 'menu.bpcsOrderCollab', cached: true },
  },
  {
    path: 'bpcs-wh-replenish',
    name: 'BpcsWhReplenish',
    component: () => import('@/views/bpcs/warehouseReplenish/index.vue'),
    meta: { title: 'menu.bpcsWhReplenish', cached: true },
  },
  {
    path: 'bpcs-control-tower',
    name: 'BpcsControlTower',
    component: () => import('@/views/bpcs/controlTower/index.vue'),
    meta: { title: 'menu.bpcsControlTower', cached: true },
  },
  {
    path: 'bpcs-cpfr',
    name: 'BpcsCpfr',
    component: () => import('@/views/bpcs/cpfr/index.vue'),
    meta: { title: 'menu.bpcsCpfr', cached: true },
  },
  {
    path: 'bpcs-tms',
    name: 'BpcsTms',
    component: () => import('@/views/bpcs/tms/index.vue'),
    meta: { title: 'menu.bpcsTms', cached: true },
  },
  {
    path: 'bpcs/wms/overview',
    name: 'WmsOverview',
    component: () => import('@/views/bpcs/wms/overview/index.vue'),
    meta: { title: 'menu.wmsOverview', cached: true },
  },
  {
    path: 'bpcs/wms/binInventory',
    name: 'WmsBinInventory',
    component: () => import('@/views/bpcs/wms/binInventory/index.vue'),
    meta: { title: 'menu.wmsBinInventory', cached: true },
  },
  {
    path: 'bpcs/wms/pickPath',
    name: 'WmsPickPath',
    component: () => import('@/views/bpcs/wms/pickPath/index.vue'),
    meta: { title: 'menu.wmsPickPath', cached: true },
  },
  {
    path: 'bpcs/wms/batchTracking',
    name: 'WmsBatchTracking',
    component: () => import('@/views/bpcs/wms/batchTracking/index.vue'),
    meta: { title: 'menu.wmsBatchTracking', cached: true },
  },
  {
    path: 'bpcs/wms/movementHistory',
    name: 'WmsMovementHistory',
    component: () => import('@/views/bpcs/wms/movementHistory/index.vue'),
    meta: { title: 'menu.wmsMovementHistory', cached: true },
  },
] satisfies RouteRecordRaw[]
